######################################################################
# Automatically generated by qmake (3.1) Thu May 9 10:53:42 2019
######################################################################
QT += widgets network gui


TEMPLATE = app

CONFIG += c++17

# Directories

FORMS += \
    maindialog.ui

HEADERS += \
    maindialog.h

SOURCES += \
    main.cpp \
    maindialog.cpp
